defaults:
  - model: gan
  - data: afhq
  - optimizer: adamw
  - scheduler: warm_up_linear
  - wandb: default
  - _self_


training:
  epochs: 120
  batch_size: 32
  image_size: 256
  pin_memory: true
  compile: false
  save_every: 40
  sample_every: 10
  eval_every: 1
  beta1: 0.5
  beta2: 0.9
  n_critic: 1

loss:
  criterion: bce # bce, wgan_gp, ragan
  label_smoothing: 0.1
  gradient_penalty: 10 # > 0 to use, only used with wgan_gp
  r1_penalty: 0 # > 0 to use
  path_length_penalty: 0 # > 0 to use


seed: 12
device: cuda # trivial, cuda is used by default in the current version

ADA:
  use_ADA: True
  ada_target_acc: 0.6
  horizontal_flip: true # to include others, ADA default is used internally

log_dir: ./logs
checkpoint_dir: ./checkpoints
sample_dir: ./samples