defaults:
  - model: gan
  - data: afhq
  - optimizer: adamw
  - scheduler: warm_up_linear
  - wandb: default
  - _self_


training:
  epochs: 120
  batch_size: 16
  image_size: 256
  pin_memory: true
  compile: true
  save_every: 40
  sample_every: 10
  eval_every: 1
  beta1: 0.5
  beta2: 0.9

loss:
  criterion: bce
  lambda_gp: 10


seed: 12
device: cuda

ADA:
  use_ADA: True
  ada_target_acc: 0.6
  horizontal_flip: true

log_dir: ./logs
checkpoint_dir: ./checkpoints
sample_dir: ./samples