defaults:
  - model: gan
  - data: afhq
  - optimizer: adamw
  - wandb: default
  - _self_


training:
  epochs: 160
  batch_size: 32
  image_size: 256
  pin_memory: true
  compile: true
  save_every: 10
  sample_every: 10
  eval_every: 10
  beta1: 0.5
  beta2: 0.9

loss:
  criterion: bce
  lambda_gp: 10


seed: 12
device: cuda

augmentations:
  use_ADA: false
  ada_target_acc: 0.6
  horizontal_flip: true

log_dir: ./logs
ckeckpoint_dir: ./checkpoints
sample_dir: ./samples