defaults:
  - model: gan
  - data: afhq
  - scheduler: warm_up_linear
  - wandb: default
  - _self_


optimizer:
  name: adam
  G_lr: 2e-5
  D_lr: 1e-5


training:
  epochs: 160
  batch_size: 32
  image_size: 256
  compile: false
  save_every: 40
  sample_every: 10
  evaluate_every: 4
  beta1: 0.5
  beta2: 0.9
  n_critic: 1

loss:
  criterion: bce # bce, hinge, wgan_gp, ragan
  grad_penalty: 0 # > 0 to use, only used with wgan_gp
  r1_penalty: 0 # > 0 to use
  path_length_penalty: 0 # > 0 to use

seed: 12
ADA:
  use_ADA: True
  ada_target_acc: 0.8

log_dir: ./logs
checkpoint_dir: ./checkpoints
sample_dir: ./samples