ADA:
  value:
    use_ADA: true
    ada_target_acc: 0.8

data:
  value:
    root_dir: "data/afhq/cat"
    image_size: 256

loss:
  value:
    criterion: ragan
    r1_penalty: 0
    grad_penalty: 0
    path_length_penalty: 0

seed:
  value: 12

model:
  value:
    leak: 0.2
    name: GAN
    norm: batch
    lat_dim: 128
    activation: elu
    spectral_norm: false
    self_attention: false
    generator:
      norm: batch
      channels:
        - 1024
        - 1024
        - 512
        - 512
        - 256
        - 128
        - 3
      init_size: 1
      activation: elu
      upsample: deconv
      attention_layers: []
    discriminator:
      norm: none
      channels:
        - 3
        - 64
        - 64
        - 128
        - 128
        - 256
        - 256
        - 512
        - 1024
      activation: elu
      spectral_norm: true

wandb:
  value:
    notes: "first run"
    project: "GANs"
    log_freq: 50
    log_grads: false
    log_params: false
    log_samples: true


training:
  value:
    beta1: 0.32
    beta2: 0.9
    epochs: 160
    compile: false
    n_critic: 4
    batch_size: 32
    image_size: 256
    save_every: 40
    sample_every: 10
    evaluate_every: 4

optimizer:
  value:
    D_lr: 0.00007
    G_lr: 0.0003
    name: adam

scheduler:
  value:
    name: warm_up_linear
    min_lr: 0.0002
    warm_up_phase: 0.01

sample_dir: "./samples"
checkpoint_dir: "./checkpoints"
log_dir: "./logs"
