ADA:
  use_ADA: true

data:
  root_dir: /kaggle/input/animal-faces/afhq/train/cat
  image_size: 256

loss:
  criterion: ragan
  r1_penalty: 0
  grad_penalty: 0
  path_length_penalty: 0

seed: 12

model:
  leak: 0.2
  name: GAN
  norm: batch
  lat_dim: 128
  generator:
    norm: batch
    channels:
      - 1024
      - 1024
      - 512
      - 512
      - 256
      - 128
      - 32
    upsample:
      - interpolation
      - interpolation
      - interpolation
      - interpolation
      - deconv
      - deconv
      - deconv
    init_size: 2
    activation: elu
    attention_layers: []
  activation: elu
  discriminator:
    norm: none
    channels:
      - 3
      - 64
      - 128
      - 256
      - 512
      - 1024
    activation: elu
    spectral_norm: true
  spectral_norm: false
  self_attention: false


wandb:
  notes: first run
  project: GANs
  log_freq: 50
  log_grads: false
  log_params: false
  log_samples: true



training:
  beta1: 0.0
  beta2: 0.9
  epochs: 160
  compile: true
  n_critic: 4
  batch_size: 32
  image_size: 256
  save_every: 40
  sample_every: 10
  evaluate_every: 4

optimizer:
  D_lr: 0.00005
  G_lr: 0.0003
  name: adam

scheduler:
  name: warm_up_linear
  min_lr: 0.0002
  warm_up_phase: 0.01

log_dir: ./logs
sample_dir: ./samples
checkpoint_dir: ./checkpoints
