defaults:
  - data: afhq
  - scheduler: warm_up_linear
  - wandb: default
  - _self_


model:
  name: GAN
  lat_dim: 128
  generator:
    channels: [512, 512, 256, 256, 128, 128, 3]
    norm: "instance"
    activation: "relu"
    use_SA: false
    use_SN: true
    init_size: 2
  discriminator:
    norm: "none"
    channels: [3, 64, 128, 128, 256, 256]
    activation: "leaky_relu"
    leak: 0.2
    use_SA: false
    use_SN: true

loss:
  criterion: "wgan_gp"
  grad_penalty: 6.0

training:
  batch_size: 32
  image_size: 256
  epochs: 160
  compile: false
  n_critic: 4
  beta1: 0.5
  beta2: 0.9
  G_lr: 0.0001
  D_lr: 0.0001
  save_every: 40
  sample_every: 10
  evaluate_every: 4

optimizer:
  name: adam
  G_lr: 2e-4
  D_lr: 5e-5

seed: 12
ADA:
  use_ADA: True
  ada_target_acc: 0.8

log_dir: ./logs
checkpoint_dir: ./checkpoints
sample_dir: ./samples